version: "3"

services:
  mysql:
    image: mysql:8.0.21 
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: e-natal_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: e-natal-api
    ports:
      - "3001:3001"
    depends_on:
      - mysql
