version: "3"

services:
  backend:
    build: .
    container_name: e-natal-api
    ports:
      - "3001:3001"
    depends_on:
      mysql: 
        condition: service_healthy
    environment: 
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - .:/app
    command: >
      sh -c "npx sequelize-cli db:drop &&
             npx sequelize-cli db:create &&
             npx sequelize-cli db:migrate &&
             npm run dev"
  mysql:
    image: mysql:8.0.21
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "3002:3306"
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores