version: "3"

services:
  backend:
    build: .
    container_name: e-natal-api
    ports:
      - "3001:3001"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.21
    container_name: mysql-container
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: e-natal_database
    ports:
        - "3306:3306"
